### ISSUE TITLE
How did you convert 300 dimensional vectors to points in 3D?

### ISSUE THREAD

**Issue by aburkov** [anvaka/word2vec-graph#1]
Hi. Your graph looks amazing, but could you please explain how did you converted each 300 dimensional word vector into a point in 3D space?

**Comment by anvaka** [comment]
The algorithm works this way:

1. Add every single point into a graph as a graph node
2. For each point find nearest neighbors with distance in 300-dimensional space smaller than a given threshold value. Add an edge into the graph between nearest neighbors. 
3. Run graph layout algorithm to compute positions of every node in the 3D space.

Does this make sense?

NB: I used default distance function from [spotify/annoy](https://github.com/spotify/annoy) as a definition of distance, which seem to be a cosine distance between two vectors.

**Comment by aburkov** [comment]
The point which is not clear for me is "Run graph layout algorithm to compute positions of every node in the 3D space."

How exactly this algorithm selects the coordinates x, y and z for each point given that the original point has 300 dimensions?

**Comment by anvaka** [comment]
The original 300 dimensions are used only to determine distance between two vectors. Distance determines whether we want to make an edge between two nodes. Once we have the graph, we run a force based [graph layout algorithm](https://en.wikipedia.org/wiki/Force-directed_graph_drawing). This algorithm doesn't know (directly) anything about original 300 dimensions of the nodes. It operates on nodes and edges of a graph, trying to come up with positions for every node, based on physical simulation.

For the sake of example, lets take these three vector embeddings:

```
cat => [0.1, 0.0, 0.9, 1.0]
dog => [0.9, 0.0, 0.0, 1.0]
cow => [0.6, 1.0, 0.5, 0.0]
```

Let's compute distance between every pair of nodes:

```
|cat - dog| = (0.1 - 0.9)^2 + (0 - 0)^2 + (0.9 - 0)^2 + (1 - 1)^2 = 1.2
|cat - cow| = 1.55
|dog - cow| = 1.53
```

Now let's build a graph. First of all, let's add all nodes. Nodes would be `cat`, `dog` and `cow`. By agreement, we will only add edges between nodes, with distance smaller than `1.5`. Which means,
our graph will look like:

```
cat <-> dog                   cow
```

(`cow` has no edges in this graph, as it is too far away from `cat` and `dog`).

Now we have a graph, we run physical simulation to find where each node should be rendered.
In this simulation we consider all nodes as charged particles, so that they repel each other. Every link is treated as a spring between nodes, so that connected nodes don't fly too far away. Initial placement of nodes is random, but after a few iterations, layout usually converges to plausible configuration, and that is exactly what we render on the screen.

As you see, we are not using original dimensions of the vector space during layout. Original dimensions are only used to determine whether two nodes have link between them or not.

**Comment by aburkov** [comment]
I see. So in your example, "cow" point in 3D can be arbitrarily far from dog and cat because there's no edge between "cow" and those two?

**Comment by anvaka** [comment]
Correct
